<%@ Page Title="" Language="C#" MasterPageFile="~/User/UserMaster.Master" AutoEventWireup="true" CodeFile="userCart.aspx.cs" Inherits="SikshaNew.User.userCart" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
<style>
        .cart-container {
            margin: 30px;
            padding: 30px;
            background-color: #ffffff;
            border-radius: 16px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.08);
            font-family: 'Inter', sans-serif;
        }

        .cart-container h2 {
            margin-bottom: 20px;
            color: #2f3640;
        }

        .styled-gridview {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        .styled-gridview th {
            background-color: #00a8ff;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: 600;
        }

        .styled-gridview td {
            background-color: #f8f9fa;
            padding: 12px;
            border-bottom: 1px solid #ddd;
        }

        .styled-gridview tr:nth-child(even) td {
            background-color: #e9ecef;
        }

        .action-buttons {
            display: flex;
            gap: 20px;
            margin-top: 20px;
        }

        .action-buttons input[type="submit"] {
            padding: 10px 20px;
            border: none;
            border-radius: 6px;
            background-color: #00a8ff;
            color: white;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .action-buttons input[type="submit"]:hover {
            background-color: #007acc;
        }
    </style>

    <title></title>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
 <div class="cart-container">
        <h2>Your Cart</h2>

        <asp:GridView ID="gvCartItems" runat="server"
            AutoGenerateColumns="False"
            DataKeyNames="SubcourseId"
            AutoGenerateDeleteButton="True"
            OnRowDeleting="gvCartItems_RowDeleting"
            CssClass="styled-gridview">

            <Columns>
                <asp:BoundField DataField="SubcourseName" HeaderText="Name" />
                <asp:BoundField DataField="SubcoursePrice" HeaderText="Price" />
                <asp:BoundField DataField="Stars" HeaderText="Stars" />
                <asp:TemplateField HeaderText="Thumbnail">
                    <ItemTemplate>
                        <asp:Image ID="imgThumb" runat="server" ImageUrl='<%# Eval("Thumbnail") %>' Width="100px" Height="60px" />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>

        <div class="action-buttons">
            <asp:Button ID="btnAddMoreCourses" runat="server" Text="Add More Courses" OnClick="btnAddMoreCourses_Click" />
            <asp:Button ID="btnCheckout" runat="server" Text="Proceed to Checkout" OnClick="btnCheckout_Click" />
        </div>
    </div>


</asp:Content>
